<?php if ($this->pageCount): ?>

    <nav>
        <ul class="pagination">

            <?php if (isset($this->previous)): ?>
                <li>
                    <a href="<?= $this->url($this->route, ['action' => 'show','id' => $this->postId], ['query'=>['page'=>$this->previous,'sortBy' => $this->sortBy, 'order' => $this->order]]); ?>" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
            <?php else: ?>
                <li>
                    <span aria-hidden="true">&laquo;</span>
                </li>
            <?php endif; ?>

            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page != $this->current): ?>
                    <li>
                        <a href="<?= $this->url($this->route, ['action' => 'show','id' => $this->postId], ['query'=>['page'=>$page,'sortBy' => $this->sortBy, 'order' => $this->order]]); ?>"><?= $this->escapeHtml($page); ?></a>
                    </li>
                <?php else: ?>
                    <li>
                        <span aria-hidden="true"><b><?= $this->escapeHtml($page); ?></b></span>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>


            <?php if (isset($this->next)): ?>
                <li>
                    <a href="<?php echo $this->url($this->route,
                        ['action' => 'show','id' => $this->postId],
                        ['query'=>['page'=>$this->next,'sortBy' => $this->sortBy, 'order' => $this->order]]); ?>" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            <?php else: ?>
                <li>
                    <span aria-hidden="true">&raquo;</span>
                </li>
            <?php endif; ?>
        </ul>
    </nav>
<?php endif; ?>