<?php

$comments = $this->comments;

function displayAttachment($attachment) {
    if($attachment['type'] == 'img') {
        echo "<img data-type=\"img\" src=\"{$attachment['path']}\" class='attachment attachment_image'>";
    } elseif ($attachment['type'] == 'txt') {
        echo "<div data-type=\"txt\" data-src=\"{$attachment['path']}\" class=\"attachment attachment_txt\"></div>";
    }
}
function renderLeafs($comments) {
    echo " <div class=\"comment-list\">";
    foreach ($comments as $comment) {
        echoComment($comment);
    }
    echo"</div>";
}


function renderRoot($comments) {
    foreach ($comments as $comment) {
        if (!$comment->getParentId()) {
            echoComment($comment);
        }
    }
}

function echoComment($comment) {
    echo "<div class=\"comment-list__item\" data-id=\"{$comment->getId()}\">";
    echo "   <div class=\"comment-list__item-head\">";
    echo "      <span>{$comment->getUsername()}</span>";
    echo "      <span>{$comment->getEmail()}</span>";
    echo "      <span>{$comment->getCreatedAt()}</span>";
    echo "   </div>";
    echo "   <div class=\"comment-list__item-body\">{$comment->getContent()}";
    displayAttachment($comment->getAttachment());
    echo"    </div>";
    echo "   <div class=\"comment-list__item-footer\">";
    if($comment->getHomepage()) {
        echo"<a class='home-page' href=\"{$comment->getHomepage()}\">Homepage</a>";
    }
    echo "      <button class=\"btn btn-primary button_reply\">Reply</button>";
    echo "   </div>";
    if($comment->hasChildren()) {
        renderLeafs($comment->getChildren());
    }
    echo "</div>";

}

?>

<div class="post">
    <div class="post__title"><h1><?=$this->post->getTitle() ?></h1></div>
    <div class="post__content">
        <?=$this->post->getContent()  ?>
    </div>

    <div class="post__comments">
        <div class="comment-order">
            <h2>Global Sort comments</h2>
            <form ref="sortForm"
                  data-lastpage="<?= $this->lastPage ?? 1 ?>"
                  data-perpage="<?= $this->perPage ?? 1 ?>"
                  data-totalitemcount="<?= $comments->getTotalItemCount() ?? 1 ?>"
                  data-currentpage="<?= $this->currentPage ?? 1 ?>" class="sort">
                <label class=""> By field
                    <select name="sortBy" id="">
                        <option <?= $sortBy == "createdAt" ? 'selected' : '' ?> value="createdAt">Date</option>
                        <option <?= $sortBy == "username" ? 'selected' : '' ?> value="username">Username</option>
                        <option <?= $sortBy == "email" ? 'selected' : '' ?> value="email">Email</option>
                    </select>
                </label>
                <label >In descending order
                    <input  <?= $order == "desc" ? 'checked' : '' ?>  name="order" type="radio"  value="desc">
                </label>
                <label >In ascending order
                    <input <?= $order == "asc" ? 'checked' : '' ?>  name="order" type="radio"  value="asc">
                </label>
                <button type="submit" class="btn btn-default">Sort</button>
            </form>
        </div>
        <h2>Comments list</h2>
        <div @click="delegateClick" class="comment-list">
            <?php renderRoot($comments) ?>
        </div>
        <div class="comment-pagination">
            <?= $this->paginationControl(
                $comments,
                'Sliding',
                'post/partial/comment_paginator',
                [
                    'route' => 'post',
                    'postId' => $this->post->getId(),
                    'sortBy' => $this->sortBy,
                    'order' => $this->order
                ]); ?>
        </div>
    </div>
</div>

<template v-if="!commentForm.data.parent_id">
    <h1>Add new comment</h1>
    <p>Please fill out the following form and click the <i>Create</i> button.</p>
</template>
<div class="row">
    <div class="col-md-6 form-origin">
        <form @submit.prevent="sendComment" ref="commentForm" action="<?= $this->url('comment',['action' => 'create','id' => $this->post->getId()]) ?>" enctype="multipart/form-data" method="POST">
            <div class="form-group">
                <label for="username">Username</label>
                <input v-model="commentForm.data.username" required type="text" name="username" id="username" placeholder="Enter your name"
                       value="" class="form-control">
                <div v-cloak v-for="error in commentForm.errors.username" class="data data_invalid">{{error}}</div>
            </div>
            <div class="form-group">
                <label for="email">Email</label>
                <input v-model="commentForm.data.email" required type="email"  name="email" id="email" placeholder="Email please..." value=""
                       class="form-control">
                <div v-cloak v-for="error in commentForm.errors.email" class="data data_invalid">{{error}}</div>
            </div>
            <div class="form-group">
                <label for="homepage">Homepage</label>
                <input v-model="commentForm.data.homepage" type="url" name="homepage" id="homepage" placeholder="Homepage..." value=""
                       class="form-control">
                <div v-cloak v-for="error in commentForm.errors.homepage" class="data data_invalid">{{error}}</div>
            </div>
            <div class="form-group">
                <label for="content">Your message...</label>
                <div @click="addTagToText" class="controls">
                    <div class="controls__button" data-tag="i">&lt;i&gt;</div>
                    <div class="controls__button" data-tag="code">&lt;code&gt;</div>
                    <div class="controls__button" data-tag="a">&lt;a&gt;</div>
                    <div class="controls__button" data-tag="strong">&lt;strong&gt;</div>
                </div>
                <textarea ref="textarea" v-model="commentForm.data.content" name="content" id="content"
                          placeholder="Type yout message" rows="6" class="form-control">
                </textarea>
                <div v-cloak v-for="error in commentForm.errors.content" class="data data_invalid">{{error}}</div>
            </div>
            <div class="form-group">
                <label for="attachment">Attachment</label>
                <input @change="handleFileUpload" ref="attachment" type="file" name="attachment" id="attachment" class="form-control">
                <div v-cloak v-for="error in commentForm.errors.attachment" class="data data_invalid">{{error}}</div>
            </div>
            <?= $this->formLabel($form->get('captcha'))?>
            <?=  $this->formElement($form->get('captcha'))?>
            <?= $this->formElementErrors($form->get('captcha'))?>
            <div v-cloak v-for="error in commentForm.errors.captcha" class="data data_invalid">{{error}}</div>
            <input v-model="commentForm.data.parent_id" type="hidden" name="parent_id" id="parent_id" value="0">
            <input ref="post_id" type="hidden" name="post_id" value="<?= $this->post->getId()?>">

            <div class="buttons-container">
                <input v-if="!commentForm.isSending"  type="submit" name="submit" id="submitbutton" value="Create" class="button_create btn btn-primary">
                <button v-else class="spinner">Loading...</button>
                <button type="button" @click="preview">Preview</button>
                <button @click="unsetReply"
                        v-if="commentForm.data.parent_id > 0" type="button" >Unset reply</button>
            </div>

            <div v-cloak v-if="commentForm.errors && Object.keys(commentForm.errors).length" class="data data_invalid">
                Oops!... looks like you have some errors
            </div>
            <div v-cloak v-if="commentForm.success" class="alert-success">Success</div>

        </form>
        <div hidden ref="clrComm" class="comment-list__item" data-id="0">
            <div class="comment-list__item-head">
                <span ref="clrCommUsername"></span>
                <span ref="clrCommEmail"></span>
                <span ref="clrCommCreatedAt"></span>
            </div>
            <div  ref="clrCommContent" class="comment-list__item-body">
            </div>
            <div class="comment-list__item-footer">
                <a hidden class="home-page" ref="clrCommHomepage" href="">Homepage</a>
                <button  class="btn btn-primary button_reply">Reply</button>
            </div>
        </div>
    </div>
</div>
<div v-cloak v-if="isLightboxShowed"
     @click.self="lightboxUnset"
     class="overlay">
    <div class="overlay__content">
        <div class="lightbox-core">
            <div v-if="isLightboxLoading" class="">Loading...</div>
            <template v-if="!isLightboxLoading">
                <div v-if="lightbox.type == 'txt' || lightbox.type == 'inlineTxt'" >
                    {{lightbox.src}}
                </div>
                <img v-if="lightbox.type == 'img'" class="lightbox-image" :src="lightbox.src" />
            </template>
        </div>
    </div>
</div>
    <!--<div class="col-md-6">
        <form ref="form" action="<?/*=$this->url('comment',['id' => $this->post->getId(), 'action' => 'create']) */?>"
              enctype="multipart/form-data"
              method="POST">

        <div class="form-group">
            <?/*= $this->formLabel($form->get('username')); */?>
            <?/*= $this->formElement($form->get('username')); */?>
            <?/*= $this->formElementErrors($form->get('username')); */?>
        </div>

        <div class="form-group">
            <?/*= $this->formLabel($form->get('email')); */?>
            <?/*= $this->formElement($form->get('email')); */?>
            <?/*= $this->formElementErrors($form->get('email')); */?>
        </div>

        <div class="form-group">
            <?/*= $this->formLabel($form->get('homepage')); */?>
            <?/*= $this->formElement($form->get('homepage')); */?>
            <?/*= $this->formElementErrors($form->get('homepage')); */?>
        </div>

        <div class="form-group">
            <?/*= $this->formLabel($form->get('content')); */?>
            <?/*= $this->formElement($form->get('content')); */?>
            <?/*= $this->formElementErrors($form->get('content')); */?>
        </div>
        <div class="form-group">
            <?/*= $this->formLabel($form->get('attachment')); */?>
            <?/*= $this->formElement($form->get('attachment')); */?>
            <?/*= $this->formElementErrors($form->get('attachment')); */?>
        </div>
        <div class="form-group">

            <?/*= $this->formLabel($form->get('captcha'))*/?>
            <?/*=  $this->formElement($form->get('captcha'))*/?>
            <?/*= $this->formElementErrors($form->get('captcha'))*/?>
        </div>



        <?/*= $this->formElement($form->get('parent_id')); */?>
        <?/*= $this->formElement($form->get('post_id')); */?>

        --><?/*= $this->formElement($form->get('submit')); */?>

<?php
//$form = $this->form;
//$form->get('username')->setAttributes([
//    'class'=>'form-control',
//    'placeholder'=>'Enter your name',
//    'required' => 'required',
//    'v-model' => "commentForm.data.username"
//
//]);
//$form->get('username')->setAttribute('v-model', "commentForm.data.username");
//$form->get('email')->setAttributes([
//    'class'=>'form-control',
//    'placeholder'=>'Email please...',
//
//]);
//$form->get('homepage')->setAttributes([
//    'class'=>'form-control',
//    'placeholder'=>'Homepage...',
//    'v-model' => "commentForm.data.homepage"
//
//]);
//
//$form->get('attachment')->setAttributes([
//    'class'=>'form-control',
//
//]);
//$form->get('content')->setAttributes([
//    'class'=>'form-control',
//    'placeholder'=>'Type yout message',
//    'rows'=>6,
//]);
//
//$form->get('parent_id')->setAttributes([
//   "value" => 0,
//]);
//
//$form->get('post_id')->setAttributes([
//    "value" => $this->post->getId(),
//]);
//
//$form->get('captcha')->setAttributes([
//    "value" => $this->post->getId(),
//    "class" => "form-control captcha-field"
//]);
//
//
//$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
//
//$form->prepare();
//
//?>


