
<div><?= $html ?></div>
<div class="post-list">
    <div class="post-list__item">
        <a href="<?= $this->url('post', ['action' => 'show', 'id' => 1]) ?>">Some static post with comments tree</a>
    </div>
    <div class="post-list__item">
        <a href="<?= $this->url('post', ['action' => 'show', 'id' => 1]) ?>">Some static post with comments tree</a>
    </div>
    <div class="post-list__item">
        <a href="<?= $this->url('post', ['action' => 'show', 'id' => 1]) ?>">Some static post with comments tree</a>
    </div>
</div>

